### ISSUE TITLE
Param type is rendering as "mixed" instead of "int" or "integer"

### ISSUE THREAD

**Issue by jc21** [victorjonsson/PHP-Markdown-Documentation-Generator#1]
In this example:

``` php
    /**
     * Refresh a Library Section.
     *
     * @param  int   $sectionKey  Obtained using getLibrarySections()
     * @param  bool  $force
     * @return null|bool
     */
    public function refreshLibrarySection($sectionKey, $force = false) {
```

The row is rendering this:

| public | <strong>refreshLibrarySection(</strong><em>mixed</em> <strong>$sectionKey</strong>, <em>bool</em> <strong>$force=false</strong>)</strong> : <em>null/bool</em><br /><em>Refresh a Library Section.</em> |

**Comment by victorjonsson** [comment]
Thanks for the report! Let me know if you find any more bugs!

**Comment by jc21** [comment]
Thanks :)
