### ISSUE TITLE
Notice Notice: Undefined offset: 1 in /vendor/victorjonsson/markdowndocs/src/PHPDocsMD/DocInfoExtractor.php on line 144

### ISSUE THREAD

**Issue by wallacemaxters** [victorjonsson/PHP-Markdown-Documentation-Generator#8]
I don't understand the cause of this error.

When I run this follow command ... :

`php phpdoc-md src/ > README.md`

... Is printed the "Notice Error" in first line of README.md

**Comment by victorjonsson** [comment]
That looks like a custom error message. What are your error settings in php.ini

**Comment by wallacemaxters** [comment]
My php.ini is set to `error_reporting = E_ALL`

**Comment by victorjonsson** [comment]
This is now fixed in [1.3.6](https://github.com/victorjonsson/PHP-Markdown-Documentation-Generator/releases/tag/1.3.6)

Let me know if you find more bugs!
